Jahia/paas_jelastic_unomi

- RELEASENOTES.md
- scripts/reset-unomi-root-password.py
- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-382
add new package to update unomi root password
> PAAS-382: add new package to update unomi root password

- scripts/reset-unomi-root-password.py
JIRA issue: https://jira.jahia.org/browse/PAAS-382
fix missing import
fix datadog missing file bug (for development envs)
fix sub regex bug for datadog : wrong replace if password starts with a number
remove useless re.search line
> PAAS-382: fix datadog file bug

- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-549
fix password retrieval when linking unomi and jahia
> PAAS-549: fix password retrieval when linking unomi and jahia

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-531
Short description: always install datadog
> PAAS-531: always install datadog

- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-651
remove baseurl
> PAAS-651: remove baseurl

- unomi.yml
- unomi_update_dx.yml
for use with new jahiastic-jcustomer images
> PAAS-596 update manifest for jahia/jahiastic-jcustomer

- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-689
handle base64 password encoding in  jelastic package
> PAAS-689: handle base64 password encoding in  jelastic package

- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-692
Linked to PR on jahiastic-jahia
Actually, it was already working on back side but it was never set up on front side, that's why.
But it has been decided that for now it should be done on back side only.
> Paas 692 add unomi key

- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-596
> Paas 596 pb with password update

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-584
add s3 and azure plugins for backups
> PAAS-584: add s3 and azure plugins for backups

- common/org.jahia.modules.jexperience.settings-global.cfg
- unomi.yml
- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-767
> Paas 767 - Install right version of jExperience module according to jCustomer version

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-849
> PAAS-849: Rename parameter from unomiVersion to productVersion

- unomi.yml
- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-974
> PAAS-974: Add support of 1.3.4 and 1.4.2

- unomi.yml
- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-963
Not sure about ES version and module link (not published yet)
> WIP PAAS-963: jCustomer 1.5.1 + jExperience 1.12

- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-974
> PAAS-974: fix incorrect elif

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-979
> PAAS-979: update elasticsearch port for jcustomer 1.5

- update.yml
JIRA issue: https://jira.jahia.org/browse/COPS-52
Adding an update JPS to update events on existing jcustomer environments
> COPS-52: adding JPS to update events

- unomi.yml
- unomi_upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-844
> Paas 844 unomi upgrade

- unomi_upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-844
> PAAS-844: update nodeGroup env vars when upgrading unomi

- unomi_upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-844
> PAAS-844: handle jahia module downgrade and add info for polling

- README.md
JIRA issue: https://jira.jahia.org/browse/PAAS-1024
> PAAS-1024: updating README

- scripts/update-jcustomer-password-in-jahia.py
- utils/set-jcustomer-password-in-jahia.yml
- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1042
> PAAS-1042: add scripts to update jCustomer password in jahia

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1080
Linked to commit: https://git.jelastic.com/jahia/elasticsearch/commit/33ffbc76066082e85b559de00281dbb5cb6771b4
The branch on gitlab elasticsearch repo should not be merged before next Jahia Cloud release
> PAAS-1080: fix ES7 cluster nok

- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1100
> PAAS-1100: Update jExperience to latest versions

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1087
> Paas 1087 persist es data

- unomi.yml
- unomi_update_dx.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1074
> PAAS-1074: handle errors (partially)

- unomi_upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-927
- Update comment for polling
> PAAS-927: Update comment for polling

- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1140
> PAAS-1140 update update.yml

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1167
> PAAS-1167 remove useless action

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1011
> PAAS-1011: fix onAfterRedeploy events for ES

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1011
> PAAS-1011 fix duplicate parameters in ES conf file

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1175
> PAAS-1175: fix retrieving of Datadog API key

- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1175
> PAAS-1175: fix update script not up-do-date

- region_migrate.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1182
> PAAS-1182 add region_migrate.yml

- unomi.yml
- unomi_update_dx.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1169
> Paas 1169 handle es scalein

- unomi.yml
- unomi_update_dx.yml
- unomi_upgrade.yml
- update.yml
- utils/set-jcustomer-password-in-jahia.yml
- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1213
> PAAS-1213: Homogenize packages metadata

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1228
> PAAS-1228: fix datadog hostname for ES nodes

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1043
> Paas 1043 fix hostname issue

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1045
> PAAS-1045: disable direct node access

- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1248
> PAAS-1248: Update jExperience installed versions

- configs/dd_agent_jelastic_package_conf.yml
- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1237
> PAAS-1237: jelastic package logging

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1157
> PAAS-1157 Switch from jahiadev/elasticsearch to jahia/jahiastic-elasticsearch

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1237
> PAAS-1237: fix permissions on backup log file

- unomi_update_dx.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1214
> PAAS-1214: concatenate unomi allowed ip with previous value

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1277
> PAAS-1277: add unomi 1.4.3 and 1.5.2

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1204
> PAAS-1204: fix updateHazelcast to avoid config line duplication

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1297
> PAAS-1297: Remove references to specific jCustomer versions

- unomi.yml
- update.yml
- utils/set-unomi-root-password.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1301
> PAAS-1301: fix password reset with update package

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1309
> PAAS-1309 fix setupDatadogAgentEs if param is a nodeId

- migrations/migration-to-v2.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1309
> PAAS-1309 update v2 migration manifest

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1184
> PAAS-1184: add root password option to unomi.yml

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1234
> PAAS-1234: remove envlink in linked jahias when jCustomer is deleted

- common/common_actions.yml
- elasticsearch/elasticsearch_actions.yml
- jcustomer/jcustomer_actions.yml
- migrations/v2/migration-to-v2.yml
- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1336
> PAAS-1336: add mixins & improve v2 migration script

- elasticsearch/elasticsearch_actions.yml
- jcustomer/jcustomer_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1336
> PAAS-1336: fix healthchecks

- region_migrate.yml
- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1344
> Paas 1344 fix previous refactoring

- jcustomer/jcustomer_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1344
> PAAS-1344: Restore wrongly deleted actions

- common/common_actions.yml
- migrations/v2/migration-to-v2.yml
- scripts/log_events.sh
- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1323
> PAAS-1323: log events in datadog

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1323
> PAAS-1323: fix log in onBeforeDelete event

- elasticsearch/elasticsearch_actions.yml
- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1378
> PAAS-1378 follow official ES procedure for redeploy/restart

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1377
> PAAS-1377: Add env check at the end of install package

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1359
> PAAS-1359: remove onUninstall event

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1377
> PAAS-1377: fix nodeid event parameter for redeploy and restart events

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1377
> PAAS-1377: fix ES node broken restart event

- unomi.yml
- update.yml
parameter nodeId
JIRA issue: https://jira.jahia.org/browse/PAAS-1378
> PAAS-1378 moving from general events to ES dedicated events, use

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1377
> PAAS-1377: fix unomi restart broken event

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1378
> PAAS-1378 handle shard allocations for stop/start env

- elasticsearch/elasticsearch_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1378
> PAAS-1378 test ES is up before enable full shards allocation

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1425
> PAAS-1425: Wait for env to be up after start

- unomi_upgrade.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1424
> PAAS-1424: Set sequential mode to false when redeploying jCustomer nodes

- common/common_actions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1435
> PAAS-1435: Check env status before logging event

- scripts/log_events.sh
JIRA issue: https://jira.jahia.org/browse/PAAS-1435
> PAAS-1435: Add silent option to log_event curl

- elasticsearch/elasticsearch_actions.yml
- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1452
Fixed the action (because needed) but also removed it from beforeStop & afterStart if only one ES node (doesn't make any sense)
> PAAS-1452: fix setShardAllocation not working for ES 5 single ES

- unomi.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1454
> PAAS-1454: purge ES data node before setup

- .github/CODEOWNERS
- README.md
- elasticsearch/elasticsearch_actions.yml
- migrations/v2/migration-to-v2.yml
- unomi.yml
- unomi_update_dx.yml
- unomi_upgrade.yml
- update.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1383
Please merge at same time as https://github.com/Jahia/jahia-cloud-modules/pull/277
> PAAS-1383: Remove unused 'package type' notion

- unomi_update_dx.yml
- utils/compare-versions.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1458
> PAAS-1458 install jexperience module following jahia version compatibility matrix

- configs/dd_jmx_unomi_conf.yaml
- migrations/v3/jcustomer_status.py
- migrations/v3/jcustomer_status.yaml
- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1422
> PAAS-1422: add custom check for jcustomer

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1453
> PAAS-1453: add JELASTIC_EXPOSE=0 env var

- unomi.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1495
> PAAS-1495: Add HN affinity for non-ES nodes

- migrations/v3/migration-to-v3.yml
JIRA issue: https://jira.jahia.org/browse/PAAS-1501
> PAAS-1501: migration script v4 -> create environments in papi
